name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-restore --no-build -o output/publish
    - name: Test 
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: output/publish
        # The desired behavior if no files are found using the provided path.        
        if-no-files-found: error # optional, default is 
        
  release-dev:
    name: Release to dev 
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.DEVSERVICEPRINCIPALS }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "kv-team3-dev"
          secrets: '*'
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: artifact
          path: deploy
      - name: Release to Dev
        uses: Azure/webapps-deploy@v2
        with:
          app-name: team3-elephant-wa-dev
          package: deploy
      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1
        with:
          # Name of the Azure Web App
            app-name: team3-elephant-wa-dev
          # Application settings using the JSON syntax set as value of secret variable: APP_SETTINGS
            app-settings-json: '[{ "name": "GlobalPassword", "value": "@Microsoft.KeyVault(SecretUri=https://kv-team3-dev.vault.azure.net/secrets/GlobalPassword)", "slotSetting": false }]'
   
  
  release-prod:
      name: Release to prod 
      environment: prod
      needs: [build, release-dev]
      runs-on: ubuntu-latest

      steps:
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.DEVSERVICEPRINCIPALS }}        
        - name: Download a Build Artifact
          uses: actions/download-artifact@v2.0.10
          with:
            name: artifact
            path: deploy
        - name: Release to Prod
          uses: Azure/webapps-deploy@v2
          with:
            app-name: wa-team3-prod
            package: deploy
        - name: Azure App Service Settings
          uses: Azure/appservice-settings@v1
          with:
            # Name of the Azure Web App
              app-name: wa-team3-prod
            # Application settings using the JSON syntax set as value of secret variable: APP_SETTINGS
              app-settings-json: '[{ "name": "GlobalPassword", "value": "@Microsoft.KeyVault(SecretUri=https://kv-team3-prod.vault.azure.net/secrets/GlobalPassword)", "slotSetting": false }]'



