name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-restore --no-build -o output/publish
    - name: Test 
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: output/publish
        # The desired behavior if no files are found using the provided path.        
        if-no-files-found: error # optional, default is 
        
  releasetodev:
    
    name: Release to dev 
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
            # Artifact name
          name: artifact
            # Destination path
          path: deploy
      - name: Release to Dev
        uses: Azure/webapps-deploy@v2
        with:
          # Name of the Azure Web App
          app-name: Team3-Elephant-Dev
          # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
          publish-profile: ${{ secrets.TEAM3_DEV_PUBLISH_PROFILE }}
          # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
          package: deploy

  releaseUat:
    name: Release to uat 
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: artifact
          path: deploy
      - name: Release to UAT
        uses: Azure/webapps-deploy@v2
        with:
          app-name: team3-elephant-wa-dev
          publish-profile: ${{ secrets.WINDOWS_DEV_PUBLISH_PROFILE }}
          package: deploy
